/**
 * Evaluating a term in a concrete finite group.
 *
 * This exists because of one bug that structural tests cannot see. A rule that
 * has quietly assumed commutativity — that treats `wu` and `uw` as the same
 * thing — produces perfectly well-formed terms, satisfies every type, and
 * passes every test one would naturally write about shapes. It is only wrong
 * about *values*, and only in a group where the order matters. So the rules are
 * checked here against groups that are not abelian, where such a mistake shows
 * up immediately as an unequal result.
 *
 * Nothing here ships. It is deliberately written as a general evaluator rather
 * than as a fixture for one test: Phase 5 introduces presented groups with
 * relations, and these same groups are the examples it will want. Moving this
 * into `app/` when that happens should be a change of directory and nothing
 * else.
 */

import { subjectTerms, type Subject } from '../../app/subject.ts';
import type { Term } from '../../app/term.ts';

/**
 * A finite group, given concretely. Elements are their own canonical keys, so
 * they can be compared with `===` and collected in a `Set`.
 */
export type FiniteGroup = {
  name: string;
  elements: string[];
  identity: string;
  multiply(left: string, right: string): string;
  invert(element: string): string;
};

/* ------------------------------------------------------------------ */
/* Permutation groups                                                  */
/* ------------------------------------------------------------------ */

type Permutation = number[];

const key = (permutation: Permutation): string => permutation.join(',');

/** `(left · right)(i) = left(right(i))`, so composition reads right to left. */
function compose(left: Permutation, right: Permutation): Permutation {
  return right.map((image) => left[image]);
}

function invertPermutation(permutation: Permutation): Permutation {
  const result = new Array<number>(permutation.length);
  permutation.forEach((image, index) => {
    result[image] = index;
  });
  return result;
}

function identityPermutation(degree: number): Permutation {
  return Array.from({ length: degree }, (_, index) => index);
}

/**
 * Close a set of generating permutations under composition. Finite by
 * construction, since there are only `degree!` permutations to find.
 */
function permutationGroup(name: string, degree: number, generators: Permutation[]): FiniteGroup {
  const found = new Map<string, Permutation>();
  const start = identityPermutation(degree);
  found.set(key(start), start);

  const queue: Permutation[] = [start];
  while (queue.length > 0) {
    const current = queue.shift()!;
    for (const generator of generators) {
      const next = compose(generator, current);
      if (!found.has(key(next))) {
        found.set(key(next), next);
        queue.push(next);
      }
    }
  }

  const table = new Map<string, Permutation>(found);

  return {
    name,
    elements: [...table.keys()].sort(),
    identity: key(start),
    multiply(left, right) {
      return key(compose(table.get(left)!, table.get(right)!));
    },
    invert(element) {
      return key(invertPermutation(table.get(element)!));
    },
  };
}

/** All permutations of `degree` points, generated by a transposition and a cycle. */
export function symmetricGroup(degree: number): FiniteGroup {
  const cycle = Array.from({ length: degree }, (_, index) => (index + 1) % degree);
  const swap = identityPermutation(degree);
  [swap[0], swap[1]] = [swap[1], swap[0]];
  return permutationGroup(`S${degree}`, degree, [cycle, swap]);
}

/**
 * The symmetries of a regular `n`-gon, as permutations of its vertices: a
 * rotation and a reflection.
 */
export function dihedralGroup(n: number): FiniteGroup {
  const rotation = Array.from({ length: n }, (_, index) => (index + 1) % n);
  const reflection = Array.from({ length: n }, (_, index) => (n - index) % n);
  return permutationGroup(`D${n}`, n, [rotation, reflection]);
}

/** The groups the rules are checked against. Both are non-abelian. */
export const TEST_GROUPS: FiniteGroup[] = [symmetricGroup(3), dihedralGroup(4)];

/* ------------------------------------------------------------------ */
/* Evaluation                                                          */
/* ------------------------------------------------------------------ */

export type Assignment = Record<string, string>;

/**
 * The value of a term when each generator takes the element the assignment
 * gives it. Throws on a generator the assignment does not name, rather than
 * silently treating it as the identity.
 */
export function evaluateTerm(term: Term, assignment: Assignment, group: FiniteGroup): string {
  switch (term.kind) {
    case 'identity':
      return group.identity;

    case 'generator': {
      const value = assignment[term.name];
      if (value === undefined) throw new Error(`No value assigned to ${term.name}.`);
      return value;
    }

    case 'product':
      return term.factors.reduce(
        (total, factor) => group.multiply(total, evaluateTerm(factor, assignment, group)),
        group.identity,
      );

    case 'inverse':
      return group.invert(evaluateTerm(term.term, assignment, group));

    case 'power': {
      const base = evaluateTerm(term.base, assignment, group);
      const repeated = term.exponent < 0 ? group.invert(base) : base;
      let total = group.identity;
      for (let count = 0; count < Math.abs(term.exponent); count += 1) {
        total = group.multiply(total, repeated);
      }
      return total;
    }
  }
}

/** Whether an equation holds under this assignment. Expressions have no truth value. */
export function equationHolds(
  subject: Subject,
  assignment: Assignment,
  group: FiniteGroup,
): boolean {
  if (subject.kind !== 'equation') {
    throw new Error('Only an equation has a truth value.');
  }
  return (
    evaluateTerm(subject.left, assignment, group) ===
    evaluateTerm(subject.right, assignment, group)
  );
}

/* ------------------------------------------------------------------ */
/* Quantifying over assignments                                        */
/* ------------------------------------------------------------------ */

export function generatorNames(subject: Subject): string[] {
  const names = new Set<string>();
  const collect = (term: Term) => {
    switch (term.kind) {
      case 'generator':
        names.add(term.name);
        break;
      case 'product':
        term.factors.forEach(collect);
        break;
      case 'inverse':
        collect(term.term);
        break;
      case 'power':
        collect(term.base);
        break;
      case 'identity':
        break;
    }
  };
  subjectTerms(subject).forEach(collect);
  return [...names].sort();
}

/**
 * Every way of assigning group elements to the given names. Exhaustive, so the
 * caller is responsible for keeping `names.length` small: this is
 * `|G|^names.length` assignments.
 */
export function* assignments(
  names: string[],
  group: FiniteGroup,
): Generator<Assignment, void, undefined> {
  if (names.length === 0) {
    yield {};
    return;
  }
  const [first, ...rest] = names;
  for (const element of group.elements) {
    for (const partial of assignments(rest, group)) {
      yield { [first]: element, ...partial };
    }
  }
}
